-- Create the backlinks table
create table if not exists public.backlinks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  url text not null,
  description text not null,
  category text not null default 'Other',
  emoji text,
  submitted_by text not null,
  submitted_email text not null,
  approved boolean not null default false,
  priority integer not null default 0
);

-- Enable Row Level Security (RLS)
alter table public.backlinks enable row level security;

-- Create policy to allow anyone to read listings
create policy "Allow public read access"
  on public.backlinks for select
  using (true);

-- Create policy to allow anyone to insert listings (public submission)
create policy "Allow public insert access"
  on public.backlinks for insert
  with check (true);

-- Create policy to allow public update access
create policy "Allow public update access"
  on public.backlinks for update
  using (true)
  with check (true);

-- Create policy to allow public delete access
create policy "Allow public delete access"
  on public.backlinks for delete
  using (true);

-- ALTER STATEMENTS (run these if your table already exists):
-- alter table public.backlinks add column if not exists approved boolean not null default false;
-- alter table public.backlinks add column if not exists priority integer not null default 0;
-- update public.backlinks set approved = true;
